import { Injectable, signal } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from '../../../environments/environment';

// These are generated by: npm run proto:gen
// If not generated yet, run: bash scripts/gen-proto.sh
import { TaskServiceClient } from './generated/TaskServiceClientPb';
import {
  GetTaskRequest,
  ListTasksRequest,
  CreateTaskRequest,
  UpdateTaskRequest,
  DeleteTaskRequest,
  StreamTasksRequest,
  TaskResponse,
  ListTasksResponse,
  DeleteTaskResponse,
} from './generated/task_pb';

export interface Task {
  id: string;
  title: string;
  description: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

@Injectable({ providedIn: 'root' })
export class GrpcTaskService {
  private client = new TaskServiceClient(environment.grpcWebUrl);

  readonly streamedTasks = signal<Task[]>([]);
  readonly isStreaming = signal(false);

  private streamCancel: (() => void) | null = null;

  listTasks(page = 1, pageSize = 20): Observable<Task[]> {
    return new Observable(observer => {
      const req = new ListTasksRequest();
      req.setPage(page);
      req.setPageSize(pageSize);

      this.client.listTasks(req, {}, (err, response: ListTasksResponse) => {
        if (err) {
          observer.error(err);
          return;
        }
        observer.next(response.getTasksList().map(this.mapTask));
        observer.complete();
      });
    });
  }

  getTask(id: string): Observable<Task> {
    return new Observable(observer => {
      const req = new GetTaskRequest();
      req.setId(id);

      this.client.getTask(req, {}, (err, response: TaskResponse) => {
        if (err) { observer.error(err); return; }
        observer.next(this.mapTask(response));
        observer.complete();
      });
    });
  }

  createTask(title: string, description: string): Observable<Task> {
    return new Observable(observer => {
      const req = new CreateTaskRequest();
      req.setTitle(title);
      req.setDescription(description);

      this.client.createTask(req, {}, (err, response: TaskResponse) => {
        if (err) { observer.error(err); return; }
        observer.next(this.mapTask(response));
        observer.complete();
      });
    });
  }

  updateTask(id: string, title: string, status: string): Observable<Task> {
    return new Observable(observer => {
      const req = new UpdateTaskRequest();
      req.setId(id);
      req.setTitle(title);
      req.setStatus(status);

      this.client.updateTask(req, {}, (err, response: TaskResponse) => {
        if (err) { observer.error(err); return; }
        observer.next(this.mapTask(response));
        observer.complete();
      });
    });
  }

  deleteTask(id: string): Observable<boolean> {
    return new Observable(observer => {
      const req = new DeleteTaskRequest();
      req.setId(id);

      this.client.deleteTask(req, {}, (err, response: DeleteTaskResponse) => {
        if (err) { observer.error(err); return; }
        observer.next(response.getSuccess());
        observer.complete();
      });
    });
  }

  // Server-streaming — pushes updates to streamedTasks signal
  startStream(filterStatus = ''): void {
    this.stopStream();
    this.isStreaming.set(true);

    const req = new StreamTasksRequest();
    req.setFilterStatus(filterStatus);

    const stream = this.client.streamTasks(req, {});

    stream.on('data', (response: TaskResponse) => {
      const incoming = this.mapTask(response);
      this.streamedTasks.update(tasks => {
        const idx = tasks.findIndex(t => t.id === incoming.id);
        if (idx >= 0) {
          const copy = [...tasks];
          copy[idx] = incoming;
          return copy;
        }
        return [incoming, ...tasks].slice(0, 50);
      });
    });

    stream.on('error', () => this.isStreaming.set(false));
    stream.on('end', () => this.isStreaming.set(false));

    this.streamCancel = () => stream.cancel();
  }

  stopStream(): void {
    this.streamCancel?.();
    this.streamCancel = null;
    this.isStreaming.set(false);
  }

  private mapTask(r: TaskResponse): Task {
    return {
      id: r.getId(),
      title: r.getTitle(),
      description: r.getDescription(),
      status: r.getStatus(),
      createdAt: r.getCreatedAt(),
      updatedAt: r.getUpdatedAt(),
    };
  }
}
